# codemap_config.py
from __future__ import annotations

from typing import Dict, List

DEFAULT_DIR_EXCLUDES = {
    ".git",
    ".hg",
    ".svn",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "venv",
    "env",
    ".idea",
    ".vscode",
    "node_modules",
    "dist",
    "build",
    "out",
    "target",
    ".next",
    ".nuxt",
    ".cache",
    ".turbo",
    ".parcel-cache",
    ".angular",
    ".gradle",
    ".terraform",
    ".terragrunt-cache",
    ".sass-cache",
    ".expo",
    ".yarn",
    ".pnpm-store",
}

DEFAULT_FILE_EXCLUDES = {
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "*.so",
    "*.dll",
    "*.dylib",
    "*.exe",
    "*.obj",
    "*.o",
    "*.a",
    "*.lib",
    "*.class",
    "*.jar",
    "*.war",
    "*.ear",
    "*.zip",
    "*.tar",
    "*.gz",
    "*.7z",
    "*.rar",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.webp",
    "*.ico",
    "*.pdf",
    "*.mp4",
    "*.mov",
    "*.avi",
    "*.mkv",
    "*.mp3",
    "*.wav",
    "*.flac",
    "*.ttf",
    "*.otf",
    "*.woff",
    "*.woff2",
    "*.DS_Store",
}

CODEMAPIGNORE_FILENAMES = [
    ".codemapignore",
    ".codemapignore.txt",
]

GITIGNORE_FILENAMES = [
    ".gitignore",
]

IMPORTANT_FILES = [
    "README",
    "README.md",
    "README.rst",
    "README.txt",
    "LICENSE",
    "LICENSE.md",
    "COPYING",
    "CHANGELOG",
    "CHANGELOG.md",
    "CONTRIBUTING",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    "CODEMAP.md",
    "docker-compose.yml",
    "docker-compose.yaml",
    "compose.yml",
    "compose.yaml",
    "Dockerfile",
    "Dockerfile.*",
    ".dockerignore",
    ".env.example",
    "env.example",
    ".env.template",
    "Makefile",
    "Justfile",
    "Taskfile.yml",
    "Taskfile.yaml",
    ".gitlab-ci.yml",
    ".github/workflows/*.yml",
    ".github/workflows/*.yaml",
    "azure-pipelines.yml",
    "Jenkinsfile",
    ".circleci/config.yml",
    "pyproject.toml",
    "requirements.txt",
    "Pipfile",
    "Pipfile.lock",
    "poetry.lock",
    "setup.py",
    "setup.cfg",
    "package.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "package-lock.json",
    "tsconfig.json",
    "vite.config.*",
    "next.config.*",
    "nuxt.config.*",
    "angular.json",
    "go.mod",
    "go.sum",
    "Cargo.toml",
    "Cargo.lock",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "gradle.properties",
    "Gemfile",
    "Gemfile.lock",
    "composer.json",
    "composer.lock",
    "*.sln",
    "*.csproj",
    "*.fsproj",
    "*.vbproj",
    "global.json",
    ".editorconfig",
    # Added: Documentation files
    "*.md",
    "*.rst",
    "*.txt",
    # Added: Python source files
    "*.py",
    # Added: JavaScript/TypeScript source files
    "*.js",
    "*.ts",
    # Added: Configuration files
    "*.json",
    "*.yaml",
    "*.yml",
    "*.toml",
    "*.ini",
    "*.cfg",
    # Added: Test files
    "test_*.py",
    "*_test.py",
    "tests/*.py",
    "test/*.py",
    # Added: Script files
    "scripts/*.py",
    "scripts/*.js",
    "bin/*",
    # Added: Development configuration
    "settings*.json",
    "config/*.json",
    "*.local.json",
]

ENTRYPOINT_HINTS = [
    "main.py",
    "__main__.py",
    "app.py",
    "server.py",
    "manage.py",
    "wsgi.py",
    "asgi.py",
    "main.ts",
    "main.js",
    "index.ts",
    "index.js",
    "server.ts",
    "server.js",
    "app.ts",
    "app.js",
    "src/main.*",
    "src/index.*",
    "src/app.*",
    "cmd/*/main.go",
    "main.go",
    "Program.cs",
    "src/Program.cs",
    "App.xaml",
    "src/main.rs",
    "bin/*",
    # Added: Script entrypoints
    "scripts/*.py",
    "scripts/*.js",
    # Added: Test entrypoints
    "test_*.py",
    "*_test.py",
    "tests/*.py",
    "test/*.py",
    # Added: CLI tools
    "cli.py",
    "cli.js",
    "command.py",
    "command.js",
]

MANIFEST_STACK_SIGNALS: Dict[str, List[str]] = {
    "Python": ["pyproject.toml", "requirements.txt", "Pipfile", "setup.py", "setup.cfg", "poetry.lock"],
    "Node.js": ["package.json", "pnpm-lock.yaml", "yarn.lock", "package-lock.json"],
    "Go": ["go.mod"],
    "Rust": ["Cargo.toml"],
    "Java": ["pom.xml", "build.gradle", "build.gradle.kts"],
    ".NET": ["*.sln", "*.csproj", "*.fsproj", "*.vbproj", "global.json"],
    "Ruby": ["Gemfile"],
    "PHP": ["composer.json"],
    "Docker": ["Dockerfile", "docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"],
    "Kubernetes": ["k8s", "kubernetes", "helm", "Chart.yaml", "values.yaml", "values.yml"],
    "Terraform": ["*.tf", "*.tfvars", ".terraform.lock.hcl"],
    "GitHub Actions": [".github/workflows/*.yml", ".github/workflows/*.yaml"],
    "GitLab CI": [".gitlab-ci.yml"],
    "Azure Pipelines": ["azure-pipelines.yml"],
    "Jenkins": ["Jenkinsfile"],
    "CircleCI": [".circleci/config.yml"],
    # Added: Testing frameworks
    "Testing": ["pytest", "unittest", "test_*.py", "*_test.py", "tests/", "test/"],
    # Added: Development tools
    "Development": ["debugpy", "dotenv", "pre-commit", "black", "flake8", "mypy", "ruff"],
    # Added: Python web frameworks
    "Python Web": ["flask", "django", "fastapi", "starlette"],
    # Added: Python utilities
    "Python Utilities": ["requests", "click", "typer", "pydantic"],
}